---
  - name: copy docker_compose yml
    copy:
      src: ../docker-compose.yml
      dest: /home/centos
  - name: docker-compose up
    become_user: centos
    shell:
      cmd: docker-compose up -d
